### ISSUE TITLE
webserver--a2enmod: not found The command '/bin/sh -c webserver--a2enmod rewrite' returned a non-zero code: 127

### ISSUE THREAD

**Issue by durino13** [prog/docker-php#1]
`$ docker build . -t wallet
Sending build context to Docker daemon   2.56kB
Step 1/14 : FROM prog/php:7.1-apache2.4-alpine3.6
 ---> 1d3f01aeb7e8
Step 2/14 : RUN webserver--add-php-mod cli iconv json mbstring pdo_mysql session tokenizer
 ---> Using cache
 ---> c17cbbe7a739
Step 3/14 : RUN webserver--a2enmod rewrite
 ---> Running in 975af003fd8d
/bin/sh: webserver--a2enmod: not found
The command '/bin/sh -c webserver--a2enmod rewrite' returned a non-zero code: 127`

**Comment by prog** [comment]
Thank you for reporting this issue. There was a bug in the docs. The correct command was `webserver--enable-apache-mod`. It is `image--apache-enable-mod` in the current version. I'm trying to add semver into docker tags to prevent unexpected BC breaks like this one in the future. Please, see the readme & stay tuned :whale2:

**Comment by durino13** [comment]
Works like a charm, thx for a quick fix ;)
